# site settings
title: Rubber on the Rocks
subtitle: Myles Enriquez
email: enri.myles@gmail.com
description: Smearing rubber and writing all about it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Myles Enriquez
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 1

# social settings
500px_url: https://500px.com/rubberontherocks
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/rubberontherocks
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
